[package]
name = "mpv-cli"
version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
enum-kinds = "0.5.1"
extension-traits = "2.0.0"
itertools = "0.14.0"
postage = "0.5.0"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = { version = "0.27.1", features = ["derive"] }
tap.workspace = true
tempfile = "3.20.0"
thiserror = "2.0.12"
tracing.workspace = true
which = "7.0.3"

[dev-dependencies]
anyhow.workspace = true
test-log = { version = "0.2.17", default-features = false, features = [
  "trace",
] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
